import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import SessionProviderWrapper from "@/components/SessionProvider";
import ReduxProvider from "@/provider/redux-provider";
import ReactQueryProvider from "@/provider/query-provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Ecoshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.png" />
      <body className={`${poppins.className} antialiased`}>
        <ReduxProvider>
          <SessionProviderWrapper>
            <NextTopLoader color="#2C742F" />
            <ReactQueryProvider>
              {children}
              <Toaster
                position="top-center"
                gutter={12}
                containerStyle={{ margin: "8px" }}
                toastOptions={{
                  success: {
                    duration: 3000,
                  },
                  error: {
                    duration: 5000,
                  },
                  style: {
                    fontSize: "16px",
                    maxWidth: "500px",
                    padding: "16px 24px",
                    backgroundColor: "white",
                    color: "black",
                  },
                }}
              />
            </ReactQueryProvider>
          </SessionProviderWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
